#!/bin/env python

import os
import sys
import subprocess

def create_git_url(module_name):
    git_url = f'git@github.com:jnvilo/ansible-role-{module_name}.git'
    return git_url

def add_submodule(module_name):
    module_path = f'roles/{module_name}'
    
    # Check if the path already exists
    if os.path.exists(module_path):
        print(f"Error: Path '{module_path}' already exists.")
        return
    
    git_url = create_git_url(module_name)
    
    # Add the submodule
    try:
        subprocess.run(['git', 'submodule', 'add', git_url, module_path], check=True)
        print(f"Submodule '{module_name}' added successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error: Failed to add submodule '{module_name}'.", e)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Please provide a module name as a command-line argument.")
    else:
        module_name = sys.argv[1]
        add_submodule(module_name)

